# Generated by Django 5.1.1 on 2024-09-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_category_alter_product_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='Product',
            name='categorias',
            field=models.ManyToManyField(to='tienda.category'),
        ),
    ]
