# Generated by Django 5.1.1 on 2024-10-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_product_categorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categorias',
            new_name='categorys',
        ),
        migrations.AlterField(
            model_name='category',
            name='imagenCategoria',
            field=models.ImageField(blank=True, null=True, upload_to='Categoria_Tienda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.FloatField(),
        ),
    ]
