# Generated by Django 5.1.1 on 2024-11-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_grupo_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupo',
            field=models.CharField(blank=True, default='Invitado', max_length=50, null=True),
        ),
    ]
